version: '2'

services:
  vitepress:
    image: langren1353/gm-script
    container_name: vitepress
    restart: always
    ports:
      - 8422:80
    build:
      context: ./
      dockerfile: ./ac-baidu/doc/Dockerfile
    volumes:
      - ./newcss:/usr/share/nginx/html/newcss
    networks:
      - my_network

  fastapi:
    image: langren1353/gm-script-api
    container_name: fastapi
    restart: always
    ports:
      - 8423:80
    build:
      context: ./ac-baidu/fastapi/
      dockerfile: Dockerfile
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
